image:
  repository: aoliynyk/nodejs-app
  pullPolicy: Always

replicaCount: 4

service:
  targetPort: 8080

#env:
#  REDIS_SESSION_HOST: redis

resources:
  limits:
    cpu: 700m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  #className: nginx
  #annotations:
  #    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  #tls:
#    enabled: true
#    secretName: benco-io-cert

