image:
  repository: aoliynyk/nodejs-app
  pullPolicy: Always

service:
  targetPort: 8080
  annotations:
     alb.ingress.kubernetes.io/target-type: 'ip'


resources:
  limits:
    cpu: 700m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  className: "alb"
  annotations:
     alb.ingress.kubernetes.io/scheme: internet-facing
