#!/usr/bin/env -S helmfile apply -f

environments:
  default:

---
helmDefaults:
  atomic: true
  wait: true
  waitForJobs: true
  historyMax: 10
  createNamespace: true

releases:
- name: app1
  namespace: webapp
  chart: ./charts/webapp
  values:
  - app-values.yaml
  - ingress:
      host: app1.aws.oliynyk.me

- name: app2
  namespace: webapp 
  chart: ./charts/webapp
  values:
  - app-values.yaml
  - ingress:
      host: app2.aws.oliynyk.me
    image:
      tag: {{ requiredEnv "IMAGE_TAG" }}

- name: app3
  namespace: webapp 
  chart: ./charts/webapp
  values:
  - app-values.yaml
  - ingress:
      host: app3.aws.oliynyk.me
    image:
       tag: {{ requiredEnv "IMAGE_TAG" }}

- name: app4
  namespace: webapp 
  chart: ./charts/webapp
  values:
  - app-values.yaml
  - ingress:
      host: app4.aws.oliynyk.me
    image:
       tag: {{ requiredEnv "IMAGE_TAG" }}

